CREATE TABLE IF NOT EXISTS voip_provisioning_requests (
  id SERIAL PRIMARY KEY,
  consultant_id VARCHAR NOT NULL REFERENCES users(id),
  provider VARCHAR NOT NULL,
  status VARCHAR DEFAULT 'pending',
  desired_prefix VARCHAR,
  desired_number VARCHAR,
  assigned_number VARCHAR,
  business_name VARCHAR,
  business_type VARCHAR DEFAULT 'sole_proprietorship',
  vat_number VARCHAR,
  fiscal_code VARCHAR,
  legal_address TEXT,
  city VARCHAR,
  province VARCHAR,
  postal_code VARCHAR,
  contact_email VARCHAR,
  contact_phone VARCHAR,
  telnyx_managed_account_id VARCHAR,
  telnyx_managed_account_api_key VARCHAR,
  telnyx_requirement_group_id VARCHAR,
  telnyx_number_order_id VARCHAR,
  telnyx_connection_id VARCHAR,
  telnyx_outbound_profile_id VARCHAR,
  telnyx_did_id VARCHAR,
  messagenet_account_id VARCHAR,
  messagenet_sip_username VARCHAR,
  sip_username VARCHAR,
  sip_password VARCHAR,
  sip_gateway VARCHAR,
  notes TEXT,
  admin_notes TEXT,
  error_log TEXT,
  estimated_activation_date DATE,
  activated_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS voip_provisioning_documents (
  id SERIAL PRIMARY KEY,
  request_id INTEGER NOT NULL REFERENCES voip_provisioning_requests(id),
  consultant_id VARCHAR NOT NULL REFERENCES users(id),
  document_type VARCHAR NOT NULL,
  file_name VARCHAR NOT NULL,
  file_path VARCHAR NOT NULL,
  file_size INTEGER,
  mime_type VARCHAR,
  status VARCHAR DEFAULT 'uploaded',
  rejection_reason TEXT,
  telnyx_document_id VARCHAR,
  uploaded_at TIMESTAMP DEFAULT NOW(),
  verified_at TIMESTAMP,
  notes TEXT
);
